# Generated by Django 3.2.7 on 2021-10-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_emprestimo_nome_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
