# Generated by Django 3.2.7 on 2021-10-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(max_length=30),
        ),
    ]
