# Generated by Django 3.2.7 on 2021-10-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ra',
        ),
    ]
